LABELS = {
    "en": {
        "invoice_title": "Offer",
        "buyer_block_title": "Buyer",
        "nif": "NIF",
        "phone": "Phone",
        "email": "Email",
        "item_description": "Description",
        "item_quantity": "Quantity",
        "item_unit_price": "Unit Price",
        "item_total": "Total",
        "summary_subtotal": "Subtotal",
        "summary_tax": "VAT",
        "summary_total": "Total amount",
        "date": "Date",
        "number": "Number",
        "payment_conditions_title": "PAYMENT TERMS",
        "thanks_a_clima": "Thank you for choosing DOMYKA",
        "bank_details": "Bank details",
        "bank_name_label": "Bank",
    },
    "es": {
        "invoice_title": "Oferta",
        "buyer_block_title": "Cliente",
        "nif": "NIF",
        "phone": "Teléfono",
        "email": "Correo",
        "item_description": "Descripción",
        "item_quantity": "Cantidad",
        "item_unit_price": "Precio unitario",
        "item_total": "Total",
        "summary_subtotal": "Subtotal",
        "summary_tax": "IVA",
        "summary_total": "Importe total",
        "date": "Fecha",
        "number": "Número",
        "payment_conditions_title": "CONDICIONES DE PAGO",
        "thanks_a_clima": "Gracias por confiar en DOMYKA",
        "bank_details": "Datos bancarios",
        "bank_name_label": "Banco",
    },
    "uk": {
        "invoice_title": "Пропозиція",
        "buyer_block_title": "Клієнт",
        "nif": "NIF",
        "phone": "Телефон",
        "email": "Ел. пошта",
        "item_description": "Опис",
        "item_quantity": "Кількість",
        "item_unit_price": "Ціна за одиницю",
        "item_total": "Разом",
        "summary_subtotal": "Проміжний підсумок",
        "summary_tax": "ПДВ",
        "summary_total": "Загальна сума",
        "date": "Дата",
        "number": "Номер",
        "payment_conditions_title": "УМОВИ ОПЛАТИ",
        "thanks_a_clima": "Дякуємо, що обрали DOMYKA",
        "bank_details": "Банківські реквізити",
        "bank_name_label": "Банк",
    },
    "ru": {
        "invoice_title": "Коммерческое предложение",
        "buyer_block_title": "Клиент",
        "nif": "NIF",
        "phone": "Телефон",
        "email": "Email",
        "item_description": "Описание",
        "item_quantity": "Количество",
        "item_unit_price": "Цена за единицу",
        "item_total": "Итого",
        "summary_subtotal": "Сумма без НДС",
        "summary_tax": "НДС",
        "summary_total": "Итоговая сумма",
        "date": "Дата",
        "number": "Номер",
        "payment_conditions_title": "УСЛОВИЯ ОПЛАТЫ",
        "thanks_a_clima": "Спасибо, что выбрали DOMYKA",
        "bank_details": "Банковские реквизиты",
        "bank_name_label": "Банк",
    },
    "de": {
        "invoice_title": "Angebot",
        "buyer_block_title": "Kunde",
        "nif": "NIF",
        "phone": "Telefon",
        "email": "E-Mail",
        "item_description": "Beschreibung",
        "item_quantity": "Menge",
        "item_unit_price": "Einzelpreis",
        "item_total": "Gesamt",
        "summary_subtotal": "Zwischensumme",
        "summary_tax": "MwSt",
        "summary_total": "Gesamtsumme",
        "date": "Datum",
        "number": "Nummer",
        "payment_conditions_title": "ZAHLUNGSBEDINGUNGEN",
        "thanks_a_clima": "Danke, dass Sie DOMYKA gewählt haben",
        "bank_details": "Bankverbindung",
        "bank_name_label": "Bank",
    },
}

