LABELS = {
    "en": {
        "invoice_title": "Offer",
        "number": "Quote number",
        "date": "Date",
        "seller_title": "Supplier Details:",
        "autonomo": "Sole trader",
        "address": "Address",
        "phone": "Phone",
        "email": "Email",
        "nif": "NIE",
        "buyer_block_title": "Client:",
        "bank_name_label": "Bank",
        "item_description": "Description",
        "item_quantity": "Quantity",
        "item_base": "Net amount",
        "item_tax": "VAT",
        "summary_subtotal": "Total Net",
        "summary_tax": "VAT",
        "summary_total": "TOTAL",
    },
    "es": {
        "invoice_title": "Presupuesto",
        "number": "Número de presupuesto",
        "date": "Fecha",
        "seller_title": "Datos del Proveedor:",
        "autonomo": "Autónomo",
        "address": "Dirección",
        "phone": "Teléfono",
        "email": "Email",
        "nif": "NIE",
        "buyer_block_title": "Cliente:",
        "bank_name_label": "Banco",
        "item_description": "Concepto",
        "item_quantity": "Cantidad",
        "item_base": "Base imp.",
        "item_tax": "IVA",
        "summary_subtotal": "Total Base Imponible",
        "summary_tax": "IVA",
        "summary_total": "TOTAL",
    },
    "uk": {
        "invoice_title": "Комерційна пропозиція",
        "number": "Номер пропозиції",
        "date": "Дата",
        "seller_title": "Дані постачальника:",
        "autonomo": "Підприємець",
        "address": "Адреса",
        "phone": "Телефон",
        "email": "Ел. пошта",
        "nif": "NIE",
        "buyer_block_title": "Клієнт:",
        "bank_name_label": "Банк",
        "item_description": "Опис",
        "item_quantity": "Кількість",
        "item_base": "Сума без ПДВ",
        "item_tax": "ПДВ",
        "summary_subtotal": "Загальна сума без ПДВ",
        "summary_tax": "ПДВ",
        "summary_total": "РАЗОМ",
    },
    "ru": {
        "invoice_title": "Коммерческое предложение",
        "number": "Номер предложения",
        "date": "Дата",
        "seller_title": "Данные поставщика:",
        "autonomo": "Предприниматель",
        "address": "Адрес",
        "phone": "Телефон",
        "email": "Email",
        "nif": "NIE",
        "buyer_block_title": "Клиент:",
        "bank_name_label": "Банк",
        "item_description": "Описание",
        "item_quantity": "Количество",
        "item_base": "Сумма без НДС",
        "item_tax": "НДС",
        "summary_subtotal": "Итого без НДС",
        "summary_tax": "НДС",
        "summary_total": "ИТОГО",
    },
    "de": {
        "invoice_title": "Angebot",
        "number": "Angebotsnummer",
        "date": "Datum",
        "seller_title": "Anbieter:",
        "autonomo": "Selbständiger",
        "address": "Adresse",
        "phone": "Telefon",
        "email": "E-Mail",
        "nif": "NIE",
        "buyer_block_title": "Kunde:",
        "bank_name_label": "Bank",
        "item_description": "Beschreibung",
        "item_quantity": "Menge",
        "item_base": "Nettobetrag",
        "item_tax": "MwSt",
        "summary_subtotal": "Netto gesamt",
        "summary_tax": "MwSt",
        "summary_total": "GESAMT",
    },
    "fr": {
        "invoice_title": "Devis",
        "number": "Numéro de devis",
        "date": "Date",
        "seller_title": "Coordonnées du fournisseur:",
        "autonomo": "Auto-entrepreneur",
        "address": "Adresse",
        "phone": "Téléphone",
        "email": "E-mail",
        "nif": "NIE",
        "buyer_block_title": "Client:",
        "bank_name_label": "Banque",
        "item_description": "Description",
        "item_quantity": "Quantité",
        "item_base": "Montant HT",
        "item_tax": "TVA",
        "summary_subtotal": "Total HT",
        "summary_tax": "TVA",
        "summary_total": "TOTAL TTC",
    },
    "pl": {
        "invoice_title": "Oferta",
        "number": "Numer oferty",
        "date": "Data",
        "seller_title": "Dane dostawcy:",
        "autonomo": "Jednoosobowa działalność",
        "address": "Adres",
        "phone": "Telefon",
        "email": "E-mail",
        "nif": "NIE",
        "buyer_block_title": "Klient:",
        "bank_name_label": "Bank",
        "item_description": "Opis",
        "item_quantity": "Ilość",
        "item_base": "Kwota netto",
        "item_tax": "VAT",
        "summary_subtotal": "Łączna kwota netto",
        "summary_tax": "VAT",
        "summary_total": "RAZEM",
    },
    "it": {
        "invoice_title": "Preventivo",
        "number": "Numero preventivo",
        "date": "Data",
        "seller_title": "Dati fornitore:",
        "autonomo": "Lavoratore autonomo",
        "address": "Indirizzo",
        "phone": "Telefono",
        "email": "E-mail",
        "nif": "NIE",
        "buyer_block_title": "Cliente:",
        "bank_name_label": "Banca",
        "item_description": "Descrizione",
        "item_quantity": "Quantità",
        "item_base": "Importo netto",
        "item_tax": "IVA",
        "summary_subtotal": "Totale netto",
        "summary_tax": "IVA",
        "summary_total": "TOTALE",
    },
}


# Spanish originals — source for LLM translation
STATIC_BLOCKS_ES = {
    "info_title": "Información Importante:",
    "info_1": "Revise medidas, cantidades y características. No se admitirán reclamaciones una vez recibido el presupuesto aceptado.",
    "info_2": "Este precio es válido por 10 días.",
    "info_3": "El ingreso en cuenta de la cantidad convenida en el presupuesto implica su aceptación y es un acuerdo privado entre ambas partes.",
    "info_4": "No se incluyen los medios mecánicos de transporte, elevación y colocación (grúa, plataforma, andamio).",
    "info_5": "Cualquier obra civil necesaria para el montaje correrá a cargo del cliente salvo que se indique lo contrario.",
    "info_6": "La limpieza del material después de la instalación no está incluida en el precio.",
    "info_7": "No se incluye la protección y seguridad del material en obra después de la descarga.",
    "info_8": "Autónomo DENYS MYKOLAIENKO no será responsable de ningún incidente que ocurra después de la descarga de equipos y materiales en el sitio de construcción.",
    "info_9": "El precio indicado en el presupuesto puede variar en función de cada cambio y modificación y se pacta con el cliente.",
    "info_10": "Para confirmarlo por favor devuelva este documento firmado y aceptado, dentro de la fecha establecida, junto con el comprobante de pago. De esta forma, confirmas que has leído todos los términos y condiciones y estás de acuerdo con ellos. También has comprobado las dimensiones y la configuración y estás de acuerdo con ellas.",
    "info_11": "",
    "firma_cliente": "Firma cliente",
    "firma_autonomo": "Firma Autónomo",
}

# Pre-built translations for common languages
STATIC_BLOCKS: dict[str, dict[str, str]] = {
    "en": {
        "info_title": "Important Information:",
        "info_1": "Please check measurements, quantities and specifications. No claims will be accepted once the accepted quote has been received.",
        "info_2": "This price is valid for 10 days.",
        "info_3": "Payment of the agreed amount implies acceptance and constitutes a private agreement between both parties.",
        "info_4": "Mechanical means of transport, lifting and placement (crane, platform, scaffolding) are not included.",
        "info_5": "Any civil works required for installation will be at the client's expense unless otherwise stated.",
        "info_6": "Cleaning of materials after installation is not included in the price.",
        "info_7": "Protection and security of materials on site after unloading is not included.",
        "info_8": "Sole trader DENYS MYKOLAIENKO will not be responsible for any incident occurring after the unloading of equipment and materials at the construction site.",
        "info_9": "The price indicated may vary according to each change and modification and is agreed with the client.",
        "info_10": "To confirm, please return this document signed and accepted within the established date, together with proof of payment. By doing so, you confirm that you have read all terms and conditions and agree with them. You have also checked the dimensions and configuration and agree with them.",
        "info_11": "",
        "firma_cliente": "Client signature",
        "firma_autonomo": "Contractor signature",
    },
    "uk": {
        "info_title": "Важлива інформація:",
        "info_1": "Перевірте розміри, кількості та характеристики. Рекламації не приймаються після отримання підписаної пропозиції.",
        "info_2": "Ця ціна дійсна протягом 10 днів.",
        "info_3": "Оплата узгодженої суми означає прийняття та є приватною угодою між сторонами.",
        "info_4": "Механічні засоби транспортування, підйому та встановлення (кран, платформа, ліси) не включено.",
        "info_5": "Будь-які цивільні роботи, необхідні для монтажу, виконуються за рахунок клієнта, якщо не вказано інше.",
        "info_6": "Прибирання після монтажу не включено у вартість.",
        "info_7": "Охорона та захист матеріалів на об'єкті після розвантаження не включені.",
        "info_8": "Підприємець DENYS MYKOLAIENKO не несе відповідальності за жодні інциденти після розвантаження обладнання та матеріалів на будівельному майданчику.",
        "info_9": "Зазначена ціна може змінюватися залежно від змін та доповнень і узгоджується з клієнтом.",
        "info_10": "Для підтвердження поверніть цей документ підписаним та прийнятим у встановлений термін разом з підтвердженням оплати.",
        "info_11": "",
        "firma_cliente": "Підпис клієнта",
        "firma_autonomo": "Підпис підрядника",
    },
    "ru": {
        "info_title": "Важная информация:",
        "info_1": "Проверьте размеры, количество и характеристики. Претензии не принимаются после получения подписанного предложения.",
        "info_2": "Цена действительна в течение 10 дней.",
        "info_3": "Оплата согласованной суммы означает принятие и является частным соглашением между сторонами.",
        "info_4": "Механические средства транспортировки, подъёма и установки (кран, платформа, леса) не включены.",
        "info_5": "Любые строительные работы, необходимые для монтажа, выполняются за счёт клиента, если не указано иное.",
        "info_6": "Уборка после монтажа не включена в стоимость.",
        "info_7": "Охрана и защита материалов на объекте после разгрузки не включены.",
        "info_8": "Предприниматель DENYS MYKOLAIENKO не несёт ответственности за инциденты после разгрузки оборудования и материалов на стройплощадке.",
        "info_9": "Указанная цена может изменяться в зависимости от изменений и согласовывается с клиентом.",
        "info_10": "Для подтверждения верните этот документ подписанным в установленный срок вместе с подтверждением оплаты.",
        "info_11": "",
        "firma_cliente": "Подпись клиента",
        "firma_autonomo": "Подпись подрядчика",
    },
    "de": {
        "info_title": "Wichtige Informationen:",
        "info_1": "Bitte überprüfen Sie Maße, Mengen und Eigenschaften. Nach Erhalt des akzeptierten Angebots werden keine Reklamationen angenommen.",
        "info_2": "Dieser Preis gilt für 10 Tage.",
        "info_3": "Die Zahlung des vereinbarten Betrags gilt als Annahme und ist eine private Vereinbarung zwischen beiden Parteien.",
        "info_4": "Mechanische Transport-, Hebe- und Montagemittel (Kran, Plattform, Gerüst) sind nicht enthalten.",
        "info_5": "Alle für die Montage erforderlichen Bauarbeiten gehen zu Lasten des Kunden, sofern nicht anders angegeben.",
        "info_6": "Die Reinigung nach der Installation ist nicht im Preis enthalten.",
        "info_7": "Schutz und Sicherheit der Materialien auf der Baustelle nach der Lieferung sind nicht enthalten.",
        "info_8": "Der Selbständige DENYS MYKOLAIENKO haftet nicht für Vorfälle nach der Entladung von Geräten und Materialien auf der Baustelle.",
        "info_9": "Der angegebene Preis kann je nach Änderungen variieren und wird mit dem Kunden vereinbart.",
        "info_10": "Zur Bestätigung senden Sie dieses Dokument bitte unterschrieben und innerhalb der festgelegten Frist zusammen mit dem Zahlungsnachweis zurück.",
        "info_11": "",
        "firma_cliente": "Unterschrift Kunde",
        "firma_autonomo": "Unterschrift Auftragnehmer",
    },
    "fr": {
        "info_title": "Informations importantes:",
        "info_1": "Veuillez vérifier les dimensions, quantités et caractéristiques. Aucune réclamation ne sera acceptée une fois le devis accepté reçu.",
        "info_2": "Ce prix est valable 10 jours.",
        "info_3": "Le paiement du montant convenu implique son acceptation et constitue un accord privé entre les deux parties.",
        "info_4": "Les moyens mécaniques de transport, de levage et de placement (grue, plateforme, échafaudage) ne sont pas inclus.",
        "info_5": "Tous les travaux de génie civil nécessaires au montage seront à la charge du client sauf indication contraire.",
        "info_6": "Le nettoyage après installation n'est pas inclus dans le prix.",
        "info_7": "La protection et la sécurité des matériaux sur le chantier après le déchargement ne sont pas incluses.",
        "info_8": "L'auto-entrepreneur DENYS MYKOLAIENKO ne sera pas responsable d'un incident survenant après le déchargement des équipements et matériaux sur le chantier.",
        "info_9": "Le prix indiqué peut varier selon les modifications et est convenu avec le client.",
        "info_10": "Pour confirmer, veuillez retourner ce document signé et accepté dans le délai imparti avec la preuve de paiement.",
        "info_11": "",
        "firma_cliente": "Signature client",
        "firma_autonomo": "Signature prestataire",
    },
}
